db.Restaurants.find();
db.Restaurants.find({}, {"restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1, "_id": 0});
db.Restaurants.find({}, {"restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1, "address.zipcode": 0, "_id": 0});
db.Restaurants.find({}, {"restaurant_id": 1, "name": 1, "borough": 1, "address.zipcode": 1, "_id": 0});
db.Restaurants.find({"borough": "Bronx"});
db.Restaurants.find({"borough": "Bronx"}).limit(5);
db.Restaurants.find({"borough": "Bronx"}).skip(5).limit(5);
db.Restaurants.find({"grades.score": {"$gt": 90}});
db.Restaurants.find({"grades.score": {"$gt": 80, "$lt": 100}});
db.Restaurants.find({"address.coord.0": {"$lt": -95.754168}});
db.Restaurants.find({cuisine: { $ne: 'American' }, score: { $gt: 70 }, lat: { $lt: -65.754168 }});
db.Restaurants.find({cuisine: { $ne: 'American' }, score: { $gt: 70 }, lon: { $lt: -65.754168 }});
db.Restaurants.find({cuisine: { $ne: 'American' }, grade: 'A', borough: { $ne: 'Brooklyn' }}).sort({ _id: -1 });
db.Restaurants.find({ name: { $regex: '^Will' }}, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
db.Restaurants.find({ name: { $regex: 'ces$' }}, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
db.Restaurants.find({ name: { $regex: 'Reg' }}, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
db.Restaurants.find({ borough: 'Bronx', cuisine: { $in: ['American', 'Chinese'] }}, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
db.Restaurants.find({ borough: { $in: ['Staten Island', 'Queens', 'Bronx', 'Brooklyn'] }}, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
db.Restaurants.find({ borough: { $nin: ['Staten Island', 'Queens', 'Bronx', 'Brooklyn'] }}, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
db.Restaurants.find({ grade: { $lt: '10' }}, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
